livementor/mikado_reborn

packages/mikado_reborn/src/components/Dropdown/Dropdown.scss
I added 100 z-index range value arbitrarily.
We will be able to change it when we'll work on the stacking contexts in the app.
=> fix(dropdown): add z-index to dropdown list

packages/doc/src/stories/Snackbar.stories.js, packages/mikado_reborn/src/assets/styles/settings/_fonts.scss, packages/mikado_reborn/src/components/Snackbar/Snackbar.scss, packages/mikado_reborn/src/components/Snackbar/Snackbar.vue, packages/mikado_reborn/src/components/Snackbar/index.ts, packages/mikado_reborn/src/components/index.ts
[MKR-5]
[MKR-5]: https://livementor.atlassian.net/browse/MKR-5
https://www.loom.com/share/37f53739b1f54e3885493b332455cc12
=> Feat(snackbar) : MKR-5 snackbar

packages/mikado_reborn/src/mixins/Button/Button.ts
=> fix(button): emit click event on click

README.md, packages/mikado_reborn/package.json, packages/mikado_reborn/src/assets/styles/framework.scss, packages/mikado_reborn/src/assets/styles/settings/_fonts.scss, packages/mikado_reborn/src/assets/styles/settings/_tokens.scss, packages/mikado_reborn/tokens/design-tokens.json
[MKR-15]
[MKR-15]: https://livementor.atlassian.net/browse/MKR-15
=> chore(design-tokens): update design tokens

packages/doc/src/stories/Card.stories.js, packages/mikado_reborn/src/components/Card/Card.scss, packages/mikado_reborn/src/components/Card/Card.vue, packages/mikado_reborn/src/components/Dropdown/Dropdown.vue
The card component now has a border and a radius variation.
⚠️ This will introduce a breaking change
=> feat(card): add border and radius variations

packages/mikado_reborn/src/components/DataTable/DataTable.scss
Reset border-collapse to be sure that border-radius is applied.
=> fix(datatable): reset border-collapse

package.json, scripts/upgrade.js, yarn.lock
[FTR-91]
[FTR-91]: https://livementor.atlassian.net/browse/FTR-91
=> chore(upgrade.js): add upgrade script

packages/doc/src/stories/NotificationBadge.stories.js, packages/mikado_reborn/src/components/NotificationBadge/NotificationBadge.scss, packages/mikado_reborn/src/components/NotificationBadge/NotificationBadge.vue, packages/mikado_reborn/src/components/NotificationBadge/index.ts, packages/mikado_reborn/src/components/index.ts
=> feat(notification-badge): add notification badge component

packages/doc/src/stories/NavItem.stories.js, packages/mikado_reborn/src/components/NavItem/NavItem.scss, packages/mikado_reborn/src/components/NavItem/NavItem.vue, packages/mikado_reborn/src/components/NavItem/NavItemGroup.scss, packages/mikado_reborn/src/components/NavItem/NavItemGroup.vue
[FRONT-29]
I changed the way we handled icons in the previous implementation of the nav element with the same way we handle icons on the buttons. This will give us consistency when using the library.
=> feat(nav-item): add nav-item types (main, sub and sub-light)

packages/doc/src/stories/Progressbar.stories.js, packages/mikado_reborn/src/components/Progressbar/Progressbar.scss, packages/mikado_reborn/src/components/Progressbar/Progressbar.vue, packages/mikado_reborn/src/components/Progressbar/index.ts, packages/mikado_reborn/src/components/index.ts
=> feat(progressbar): add progressbar

packages/doc/src/stories/ExpansionPanel.stories.js, packages/mikado_reborn/src/components/ExpansionPanel/ExpansionPanel.scss, packages/mikado_reborn/src/components/ExpansionPanel/ExpansionPanel.vue
This PR adds an `activator` slot to enable custom header
=> :fix(expansion-panel): send event on header click

packages/doc/src/stories/PopUp.stories.js, packages/mikado_reborn/src/components/PopUp/PopUp.vue
Add `dismissable` property to allow pop-up to close when clicking outside of it.
=> feat(pop-up): add dismissable prop

packages/doc/src/stories/Tooltip.stories.js, packages/mikado_reborn/src/components/Tooltip/Tooltip.vue
Need disabled prop to disable tooltip when pop-up is open for example.
=> fix(tooltip): add missing disabled prop

packages/doc/src/stories/Modal.stories.js, packages/mikado_reborn/src/components/Modal/Modal.vue, packages/mikado_reborn/src/components/Modal/focusTrap.ts
=> feat(modal): add focus trap

packages/mikado_reborn/src/components/Icon/Icon.vue, packages/mikado_reborn/src/mixins/Button/Button.ts
=> refactor(button|icon): correct prop declaration

packages/mikado_reborn/src/mixins/Button/Button.scss
- Et fix aussi l'erreur de compilation SASS avec la valeur negative sur la CSS var()
=> fix(button): correct style of border on focus-visible

packages/doc/src/stories/List.stories.js, packages/mikado_reborn/src/components/List/List.scss, packages/mikado_reborn/src/components/List/List.vue, packages/mikado_reborn/src/components/List/ListItem.scss, packages/mikado_reborn/src/components/List/ListItem.vue, packages/mikado_reborn/src/components/List/index.ts, packages/mikado_reborn/src/components/index.ts
=> feat(List): new component to handle list

packages/mikado_reborn/src/components/NavItem/NavItem.ts
=> feat(nav-item): avoid error with prop declaration

packages/mikado_reborn/src/components/Progressbar/Progressbar.scss, packages/mikado_reborn/src/components/Progressbar/Progressbar.vue
Remove emoji if it is not displayed.
=> fix(progress-bar): remove emoji from dom if shrinked

packages/doc/src/stories/Progressbar.stories.js, packages/mikado_reborn/src/components/Progressbar/Progressbar.vue
https://www.figma.com/file/t3Tz3tkERrOwg42esRbLeH/Mikado-Reborn?node-id=2243%3A0
=> feat(Progressbar): add hideState property

packages/mikado_reborn/src/components/Progressbar/Progressbar.scss, packages/mikado_reborn/src/components/Progressbar/Progressbar.vue
https://www.figma.com/file/t3Tz3tkERrOwg42esRbLeH/Mikado-Reborn?node-id=2243%3A0
=> feat(Progressbar): add size property with small variation

packages/doc/src/stories/Stepper.stories.js, packages/mikado_reborn/src/components/Button/Contained/ContainedButton.scss, packages/mikado_reborn/src/components/Stepper/Stepper.scss, packages/mikado_reborn/src/components/Stepper/Stepper.vue, packages/mikado_reborn/src/components/Stepper/StepperIcon.vue, packages/mikado_reborn/src/components/Stepper/index.ts, packages/mikado_reborn/src/components/index.ts
- New stepper component
- add weight on contained button theme class
=> feat: stepper component
